#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor HDMI-A-0 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-A-0 -d I II III IV V VI

bspc config border_width 2
bspc config focused_border_color \#98fffd
bspc config normal_border_color \#181a29
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Autostart
# dunst &
# $HOME/.config/bspwm/lowbattery &
# nm-applet &
lxsession &
setxkbmap -layout latam &
timedatectl set-timezone America/Mexico_City &
timedatectl set-ntp TRUE &
feh --bg-fill ~/wallpapers/normal/23.jpg &
picom -b &
# picom &
# nitrogen --restore &
$HOME/.config/polybar/launch.sh &
