#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep  "HDMI-1 connected") ]] then
    $(bspc monitor HDMI-1 -s)
    $(bspc monitor HDMI-1 -d I II III IV V)
    $(bspc monitor LVDS-1 -d VI VII VIII IX X)
    $(sh ~/.config/screen_config/dual_monitor.sh)
else 
    $(bspc monitor LVDS-1 -s)
    $(bspc monitor LVDS-1 -d I II III IV V)
    $(bspc monitor HDMI-1 -d VI VII VIII IX X)
    $(sh ~/.config/screen_config/single_monitor.sh)
fi

bspc config border_width 3
bspc config focused_border_color \#c0caf5
spc config normal_border_color \#414868
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#!/bin/bash
#xrandr --newmode "1920x1080_60.00" 148.50 1920 2008 2052 2200 1080 1084 1089 1125 +HSync +VSync
#xrandr --addmode HDMI-1 1920x1080_60.00
#xrandr --output HDMI-1 --mode 1920x1080_60.00 --pos 0x0

# Autostart
# dunst &
/usr/bin/prime-offload &
nm-applet &
lxsession &
setxkbmap -layout latam &
timedatectl set-timezone America/Mexico_City &
timedatectl set-ntp TRUE &
# picom -b &
parcellite &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
wmname compiz & # Fix for some java apps

#For left handed mouse and touchpad with xinput
#xinput set-prop $(xinput | grep -i "usb optical mouse" | awk -F'id=' '{print $2}' | awk '{print $1}') 'libinput Left Handed Enabled' 1 &
#xinput set-prop $(xinput | grep -i "etps/2 elantech touchpad" | awk -F'id=' '{print $2}' | awk '{print $1}') 'libinput Left Handed Enabled' 1 &
