require('settings')
require('keymappings')
require('plugins')

-- Plugins Config
require('config.neodev')
require('config.dap')
require('config.lsp')
require('config.catppuccin')
require('config.telescope')
require('config.lualine')
require('config.gruvbox')
require('config.nightfox')
require('config.colorizer')
require('config.identBlackline')
require('config.nt')
require('config.tokyonight')
