[window]
padding = { x = 5, y = 5 }
opacity = 1.0
decorations = "full"

[scrolling]
history = 10000

[font]
size = 12.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[cursor.style]
shape = "Block"

[bell]
animation = "Linear"
duration = 0

[colors.primary]
background = "#11121D"
foreground = "#A0A8CD"

[colors.cursor]
cursor = "#FFFFFF" 
text = "#11121D"

[colors.selection]
background = "#262B3D"
foreground = "#A0A8CD"

[colors.normal]
black   = "#06080A"
red     = "#EE6D85"
green   = "#95C561"
yellow  = "#D7A65F"
blue    = "#7199EE"
magenta = "#A485DD"
cyan    = "#38A89D"
white   = "#A0A8CD"

[colors.bright]
black   = "#4A5057"
red     = "#FE6D85"
green   = "#98C379"
yellow  = "#F6955B"
blue    = "#9FBBF3"
magenta = "#A485DD"
cyan    = "#38A89D"
white   = "#FFFFFF"

[[colors.indexed_colors]]
index = 16
color = "#773440"

[[colors.indexed_colors]]
index = 17
color = "#587738"

[[colors.indexed_colors]]
index = 18
color = "#2A3A5A"

[[colors.indexed_colors]]
index = 19
color = "#1E2326"

[[colors.indexed_colors]]
index = 20
color = "#262B3D"

[[colors.indexed_colors]]
index = 21
color = "#281B27"

[[colors.indexed_colors]]
index = 22
color = "#1C4474"

[[keyboard.bindings]]
key = "Minus"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control|Shift"
action = "IncreaseFontSize"
